name: GitHub-Profile-Summary-Cards

on:
  schedule:
    # Runs every 24 hours (at 00:00 UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # You can specify the theme here. Options include:
          # github, github_dark, rad, noctis_minimus, tokyonight, solarized_light, etc.
          THEME: tokyonight
